name: Unit Tests

on:
  push:
    branches:
      - origin
  pull_request:
    branches: [origin]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          npm install 
          npm run test:workflow
